service: aws-shopping-cart

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 10

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  products:
    handler: functions/products.handler
    events:
      - http:
          path: products
          method: get
  get-cart:
    handler: functions/get-cart.handler
    events:
      - http:
          path: cart
          method: post
  update-cart:
    handler: functions/update-cart.handler
    events:
      - http:
          path: cart
          method: put
  clear-cart:
    handler: functions/clear-cart.handler
    events:
      - http:
          path: cart
          method: delete

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shopping_carts
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  dynamodb:
    start:
      migration: true
      seed: true
    seed:
      test:
        sources:
          - table: products
            sources: [./seeds/products.json]
          - table: shopping_carts
            sources: [./seeds/shoppingCarts.json]
    stages:
      - ${self:provider.stage}
